-- ***********************************************************************************
--                              INITIAL SCHEMA
-- ***********************************************************************************

CREATE TABLE IF NOT EXISTS public.priorities
(
    id             bigint                                             NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    level          integer                                            NOT NULL,
    name           character varying(50) COLLATE pg_catalog."default" NOT NULL,
    color_hex_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    icon_url       character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT priorities_pkey PRIMARY KEY (id),
    CONSTRAINT uk_priorities_name UNIQUE (name),
    CONSTRAINT uk_priorities_level UNIQUE (level)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id          bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name        character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id          bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name        character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT uk_permissions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id       bigint NOT NULL,
    permission_id bigint NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id)
);

-- Users with OAuth2 support: password_hash is nullable (OAuth2-only auth)
CREATE TABLE IF NOT EXISTS public.users
(
    id             bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email          character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username       character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash  character varying(255) COLLATE pg_catalog."default",
    oauth_provider character varying(50) COLLATE pg_catalog."default",
    oauth_id       character varying(255) COLLATE pg_catalog."default",
    display_name   character varying(255) COLLATE pg_catalog."default",
    avatar_url     character varying(2048) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_oauth UNIQUE (oauth_provider, oauth_id)
);

CREATE TABLE IF NOT EXISTS public.groups
(
    id          bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name        character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT groups_pkey PRIMARY KEY (id),
    CONSTRAINT uk_groups_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.action_types
(
    id   bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT action_types_pkey PRIMARY KEY (id),
    CONSTRAINT uk_action_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.issue_link_types
(
    id          bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name        character varying(100) COLLATE pg_catalog."default" NOT NULL,
    inward_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT issue_link_types_pkey PRIMARY KEY (id),
    CONSTRAINT uk_issue_link_types_name UNIQUE (name),
    CONSTRAINT uk_issue_link_types_inward_name UNIQUE (inward_name)
);

CREATE TABLE IF NOT EXISTS public.issue_types
(
    id          bigint                                             NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name        character varying(50) COLLATE pg_catalog."default" NOT NULL,
    icon_url    character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT issue_types_pkey PRIMARY KEY (id),
    CONSTRAINT uk_issue_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.issue_statuses
(
    id          bigint                                             NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name        character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT issue_statuses_pkey PRIMARY KEY (id),
    CONSTRAINT uk_issue_statuses_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.workflows
(
    id   bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT workflows_pkey PRIMARY KEY (id),
    CONSTRAINT uk_workflows_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.workflow_statuses
(
    workflow_id bigint NOT NULL,
    status_id   bigint NOT NULL,
    CONSTRAINT workflow_statuses_pkey PRIMARY KEY (workflow_id, status_id)
);

CREATE TABLE IF NOT EXISTS public.workflow_transitions
(
    id             bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name           character varying(255) COLLATE pg_catalog."default" NOT NULL,
    from_status_id bigint NOT NULL,
    to_status_id   bigint NOT NULL,
    workflow_id    bigint NOT NULL,
    CONSTRAINT workflow_transitions_pkey PRIMARY KEY (id),
    CONSTRAINT uk_workflow_transitions_unique_pair UNIQUE (workflow_id, name, from_status_id, to_status_id)
);

CREATE TABLE IF NOT EXISTS public.file_types
(
    id        bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    extension character varying(20) COLLATE pg_catalog."default" NOT NULL,
    mime_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT file_types_pkey PRIMARY KEY (id),
    CONSTRAINT uk_file_types_extension_mime_type UNIQUE (extension, mime_type)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id                  bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    key                 character varying(50) COLLATE pg_catalog."default"  NOT NULL,
    name                character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description         text COLLATE pg_catalog."default",
    lead_id             bigint                                              NOT NULL,
    default_workflow_id bigint,
    created_at          timestamp(6) without time zone                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamp(6) without time zone                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT uk_projects_key UNIQUE (key),
    CONSTRAINT uk_projects_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.project_members
(
    project_id bigint NOT NULL,
    group_id   bigint NOT NULL,
    role_id    bigint NOT NULL,
    CONSTRAINT project_members_pkey PRIMARY KEY (project_id, group_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.issues
(
    id            bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    key           character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title         character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description   text COLLATE pg_catalog."default",
    performer_id  bigint,
    issue_type_id bigint,
    priority_id   bigint,
    reporter_id   bigint                                              NOT NULL,
    status_id     bigint,
    workflow_id   bigint,
    project_id    bigint                                              NOT NULL,
    created_at    timestamp(6) without time zone                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamp(6) without time zone                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT issues_pkey PRIMARY KEY (id),
    CONSTRAINT uk_issues_key UNIQUE (key)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id         bigint                            NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    issue_id   bigint                            NOT NULL,
    author_id  bigint                            NOT NULL,
    content    text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.activity_log
(
    id             bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    issue_id       bigint                                              NOT NULL,
    user_id        bigint                                              NOT NULL,
    action_type_id bigint                                              NOT NULL,
    field_name     character varying(100) COLLATE pg_catalog."default" NOT NULL,
    old_value      text COLLATE pg_catalog."default",
    new_value      text COLLATE pg_catalog."default",
    created_at     timestamp(6) without time zone                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT activity_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attachments
(
    id              bigint                                               NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    issue_id        bigint                                               NOT NULL,
    author_id       bigint                                               NOT NULL,
    file_name       character varying(255) COLLATE pg_catalog."default"  NOT NULL,
    file_type_id    bigint                                               NOT NULL,
    file_size_bytes bigint                                               NOT NULL,
    storage_path    character varying(4096) COLLATE pg_catalog."default" NOT NULL,
    description     text COLLATE pg_catalog."default",
    updated_at      timestamp(6) without time zone                       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attachments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.issue_links
(
    id              bigint                         NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    source_issue_id bigint                         NOT NULL,
    target_issue_id bigint                         NOT NULL,
    link_type_id    bigint                         NOT NULL,
    created_at      timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT issue_links_pkey PRIMARY KEY (id),
    CONSTRAINT uk_issue_links_unique_pair UNIQUE (source_issue_id, target_issue_id, link_type_id)
);

CREATE TABLE IF NOT EXISTS public.issue_watchers
(
    issue_id bigint NOT NULL,
    user_id  bigint NOT NULL,
    CONSTRAINT issue_watchers_pkey PRIMARY KEY (issue_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.project_issue_type_workflow_defaults
(
    project_id    bigint NOT NULL,
    issue_type_id bigint NOT NULL,
    workflow_id   bigint NOT NULL,
    CONSTRAINT project_issue_type_workflow_defaults_pkey PRIMARY KEY (project_id, issue_type_id, workflow_id)
);

CREATE TABLE IF NOT EXISTS public.notification_templates
(
    id               bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name             character varying(100) COLLATE pg_catalog."default" NOT NULL,
    subject_template text COLLATE pg_catalog."default",
    body_template    text COLLATE pg_catalog."default"                   NOT NULL,
    template_type    character varying(50) COLLATE pg_catalog."default"  NOT NULL,
    is_active        boolean                                             NOT NULL DEFAULT TRUE,
    created_at       timestamp(6) without time zone                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       timestamp(6) without time zone                      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
    CONSTRAINT uk_notification_templates_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.user_notification_settings
(
    id                bigint                                             NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id           bigint                                             NOT NULL,
    notification_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_enabled        boolean                                            NOT NULL DEFAULT TRUE,
    CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_notification_settings_unique UNIQUE (user_id, notification_type)
);

CREATE TABLE IF NOT EXISTS public.notification_statuses
(
    id          bigint                                             NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name        character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT notification_statuses_pkey PRIMARY KEY (id),
    CONSTRAINT uk_notification_statuses_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.notification_queue
(
    id              bigint                         NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    recipient_id    bigint,
    recipient_email character varying(255) COLLATE pg_catalog."default",
    template_id     bigint,
    issue_id        bigint,
    project_id      bigint,
    payload         jsonb,
    status_id       bigint                         NOT NULL,
    sent_at         timestamp(6) without time zone,
    failed_attempts integer                        NOT NULL DEFAULT 0,
    created_at      timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notification_queue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_groups
(
    user_id  bigint NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT user_groups_pkey PRIMARY KEY (user_id, group_id)
);

-- ***********************************************************************************
--                              FOREIGN KEYS
-- ***********************************************************************************

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_performer FOREIGN KEY (performer_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_issue_type FOREIGN KEY (issue_type_id)
        REFERENCES public.issue_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_reporter FOREIGN KEY (reporter_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_priority FOREIGN KEY (priority_id)
        REFERENCES public.priorities (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_status FOREIGN KEY (status_id)
        REFERENCES public.issue_statuses (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_workflow FOREIGN KEY (workflow_id)
        REFERENCES public.workflows (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_project FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_projects_lead FOREIGN KEY (lead_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_projects_default_workflow FOREIGN KEY (default_workflow_id)
        REFERENCES public.workflows (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_statuses
    ADD CONSTRAINT fk_workflow_statuses_status FOREIGN KEY (status_id)
        REFERENCES public.issue_statuses (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_statuses
    ADD CONSTRAINT fk_workflow_statuses_workflow FOREIGN KEY (workflow_id)
        REFERENCES public.workflows (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_transitions
    ADD CONSTRAINT fk_workflow_transitions_workflow FOREIGN KEY (workflow_id)
        REFERENCES public.workflows (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_transitions
    ADD CONSTRAINT fk_workflow_transitions_from_status FOREIGN KEY (from_status_id)
        REFERENCES public.issue_statuses (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_transitions
    ADD CONSTRAINT fk_workflow_transitions_to_status FOREIGN KEY (to_status_id)
        REFERENCES public.issue_statuses (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comments_issue FOREIGN KEY (issue_id)
        REFERENCES public.issues (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comments_author FOREIGN KEY (author_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.activity_log
    ADD CONSTRAINT fk_activity_log_issue FOREIGN KEY (issue_id)
        REFERENCES public.issues (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.activity_log
    ADD CONSTRAINT fk_activity_log_action_type FOREIGN KEY (action_type_id)
        REFERENCES public.action_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.activity_log
    ADD CONSTRAINT fk_activity_log_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT fk_attachments_issue FOREIGN KEY (issue_id)
        REFERENCES public.issues (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT fk_attachments_uploader FOREIGN KEY (author_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT fk_attachments_file_type FOREIGN KEY (file_type_id)
        REFERENCES public.file_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issue_links
    ADD CONSTRAINT fk_issue_links_source_issue FOREIGN KEY (source_issue_id)
        REFERENCES public.issues (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.issue_links
    ADD CONSTRAINT fk_issue_links_target_issue FOREIGN KEY (target_issue_id)
        REFERENCES public.issues (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.issue_links
    ADD CONSTRAINT fk_issue_links_type FOREIGN KEY (link_type_id)
        REFERENCES public.issue_link_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issue_watchers
    ADD CONSTRAINT fk_issue_watchers_issue FOREIGN KEY (issue_id)
        REFERENCES public.issues (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.issue_watchers
    ADD CONSTRAINT fk_issue_watchers_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES public.permissions (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_project_members_project FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_project_members_group FOREIGN KEY (group_id)
        REFERENCES public.groups (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_project_members_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.project_issue_type_workflow_defaults
    ADD CONSTRAINT fk_pitwd_project FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.project_issue_type_workflow_defaults
    ADD CONSTRAINT fk_pitwd_issue_type FOREIGN KEY (issue_type_id)
        REFERENCES public.issue_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.project_issue_type_workflow_defaults
    ADD CONSTRAINT fk_pitwd_workflow FOREIGN KEY (workflow_id)
        REFERENCES public.workflows (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.user_notification_settings
    ADD CONSTRAINT fk_user_notification_settings_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_recipient_user FOREIGN KEY (recipient_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_template FOREIGN KEY (template_id)
        REFERENCES public.notification_templates (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_issue FOREIGN KEY (issue_id)
        REFERENCES public.issues (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_project FOREIGN KEY (project_id)
        REFERENCES public.projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_status FOREIGN KEY (status_id)
        REFERENCES public.notification_statuses (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.user_groups
    ADD CONSTRAINT fk_user_groups_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.user_groups
    ADD CONSTRAINT fk_user_groups_group FOREIGN KEY (group_id)
        REFERENCES public.groups (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT;

-- ***********************************************************************************
--                              INDEXES FOR PERFORMANCE
-- ***********************************************************************************

CREATE INDEX IF NOT EXISTS idx_notification_templates_name ON public.notification_templates (name);
CREATE INDEX IF NOT EXISTS idx_groups_name ON public.groups (name);
CREATE INDEX IF NOT EXISTS idx_action_types_name ON public.action_types (name);
CREATE INDEX IF NOT EXISTS idx_issue_statuses_name ON public.issue_statuses (name);
CREATE INDEX IF NOT EXISTS idx_issue_types_name ON public.issue_types (name);
CREATE INDEX IF NOT EXISTS idx_permissions_name ON public.permissions (name);
CREATE INDEX IF NOT EXISTS idx_priorities_name ON public.priorities (name);
CREATE INDEX IF NOT EXISTS idx_roles_name ON public.roles (name);
CREATE INDEX IF NOT EXISTS idx_workflows_name ON public.workflows (name);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);
CREATE INDEX IF NOT EXISTS idx_users_oauth ON public.users (oauth_provider, oauth_id);
