BEGIN;

-- ***********************************************************************************
--                              DROP TABLE
-- ***********************************************************************************

DROP TABLE IF EXISTS public.project_issue_type_workflow_defaults CASCADE;
DROP TABLE IF EXISTS public.project_members CASCADE;
DROP TABLE IF EXISTS public.user_groups CASCADE;
DROP TABLE IF EXISTS public.groups CASCADE;
DROP TABLE IF EXISTS public.role_permissions CASCADE;
DROP TABLE IF EXISTS public.permissions CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.issue_watchers CASCADE;
DROP TABLE IF EXISTS public.issue_links CASCADE;
DROP TABLE IF EXISTS public.issue_link_types CASCADE;
DROP TABLE IF EXISTS public.attachments CASCADE;
DROP TABLE IF EXISTS public.file_types CASCADE;
DROP TABLE IF EXISTS public.activity_log CASCADE;
DROP TABLE IF EXISTS public.action_types CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.notification_statuses CASCADE;
DROP TABLE IF EXISTS public.notification_queue CASCADE;
DROP TABLE IF EXISTS public.user_notification_settings CASCADE;
DROP TABLE IF EXISTS public.notification_templates CASCADE;
DROP TABLE IF EXISTS public.issues CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.workflow_transitions CASCADE;
DROP TABLE IF EXISTS public.workflow_statuses CASCADE;
DROP TABLE IF EXISTS public.issue_statuses CASCADE;
DROP TABLE IF EXISTS public.issue_types CASCADE;
DROP TABLE IF EXISTS public.priorities CASCADE;
DROP TABLE IF EXISTS public.workflows CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ***********************************************************************************
--                              MAKE TABLE
-- ***********************************************************************************

CREATE TABLE IF NOT EXISTS public.issue_types(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(50) COLLATE pg_catalog."default" NOT NULL,
icon_url character varying(255) COLLATE pg_catalog."default",
description text COLLATE pg_catalog."default",
CONSTRAINT issue_types_pkey PRIMARY KEY (id),
CONSTRAINT uk_issue_types_name UNIQUE (name));

COMMENT ON TABLE public.issue_types IS 'Opredelyaet razlichnye kategorii zadach, kotorye mogut byt sozdany v sisteme (naprimer: Bag, Zadacha, Polzovatelskaya istoriya, Epik). Pozvolyaet klassifitsirovat rabotu.';

COMMENT ON COLUMN public.issue_types.id IS 'Unikalnyy identifikator tipa zadachi.';
COMMENT ON COLUMN public.issue_types.name IS 'Nazvanie tipa zadachi.';
COMMENT ON COLUMN public.issue_types.icon_url IS 'Put k ikonke dlya vizualnogo predstavleniya tipa zadachi.';
COMMENT ON COLUMN public.issue_types.description IS 'Opisanie tipa zadachi.';

COMMENT ON CONSTRAINT uk_issue_types_name ON public.issue_types IS 'Znachenie polya `public.issue_types.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.issues(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
description text COLLATE pg_catalog."default",
key character varying(255) COLLATE pg_catalog."default" NOT NULL,
title character varying(255) COLLATE pg_catalog."default" NOT NULL,
updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
assignee_id bigint,
issue_type_id bigint,
priority_id bigint,
reporter_id bigint NOT NULL,
status_id bigint,
workflow_id bigint,
project_id bigint NOT NULL,
CONSTRAINT issues_pkey PRIMARY KEY (id),
CONSTRAINT uk_issues_key UNIQUE (key));

COMMENT ON TABLE public.issues IS 'Osnovnaya tablitsa, khranyashchaya vse zadachi (Issues) v sisteme. Eto mogut byt bagi, zadachi, istorii i t.d.';

COMMENT ON COLUMN public.issues.id IS 'Unikalnyy identifikator zadachi.';
COMMENT ON COLUMN public.issues.created_at IS 'Vremennaya metka sozdaniya.';
COMMENT ON COLUMN public.issues.description IS 'Podrobnoe opisanie zadachi.';
COMMENT ON COLUMN public.issues.key IS 'Unikalnyy klyuch zadachi (naprimer, "PROJ-123").';
COMMENT ON COLUMN public.issues.title IS 'Kratkoe opisanie zadachi.';
COMMENT ON COLUMN public.issues.updated_at IS 'Vremennaya metka poslednego obnovleniya.';
COMMENT ON COLUMN public.issues.assignee_id IS 'Ssylka na polzovatelya, kotoromu naznachena zadacha.';
COMMENT ON COLUMN public.issues.issue_type_id IS 'Ssylka na tip zadachi.';
COMMENT ON COLUMN public.issues.priority_id IS 'Ssylka na prioritet zadachi.';
COMMENT ON COLUMN public.issues.reporter_id IS 'Ssylka na polzovatelya, kotoryy sozdal zadachu.';
COMMENT ON COLUMN public.issues.status_id IS 'Ssylka na tekushchiy status zadachi.';
COMMENT ON COLUMN public.issues.workflow_id IS 'Ssylka na rabochiy protsess, kotoryy v dannyy moment ispolzuetsya dlya etoy zadachi.';
COMMENT ON COLUMN public.issues.project_id IS 'Ssylka na proekt, k kotoromu otnositsya zadacha.';

COMMENT ON CONSTRAINT uk_issues_key ON public.issues IS 'Znachenie polya `public.issues.key` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.priorities(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
level integer NOT NULL,
name character varying(50) COLLATE pg_catalog."default" NOT NULL,
icon_url character varying(255) COLLATE pg_catalog."default",
color_hex_code character varying(20) COLLATE pg_catalog."default",
CONSTRAINT priorities_pkey PRIMARY KEY (id),
CONSTRAINT uk_priorities_name UNIQUE (name),
CONSTRAINT uk_priorities_level UNIQUE (level));

COMMENT ON TABLE public.priorities IS 'Opredelyaet uroven srochnosti ili vazhnosti zadachi (naprimer, "Highest" (Vysochayshiy), "High" (Vysokiy), "Medium" (Sredniy), "Low" (Nizkiy)). Vliyaet na poryadok vypolneniya zadach.';

COMMENT ON COLUMN public.priorities.id IS 'Unikalnyy identifikator prioriteta.';
COMMENT ON COLUMN public.priorities.level IS 'Chislovoe znachenie, opredelyayushchee poryadok sortirovki ili ierarkhiyu prioritetov.';
COMMENT ON COLUMN public.priorities.name IS 'Nazvanie prioriteta.';
COMMENT ON COLUMN public.priorities.icon_url IS 'Put k ikonke dlya vizualnogo predstavleniya prioriteta.';
COMMENT ON COLUMN public.priorities.color_hex_code IS 'Shestnadtsaterichnyy kod tsveta dlya vizualnogo vydeleniya prioriteta: #RRGGBB';

COMMENT ON CONSTRAINT uk_priorities_name ON public.priorities IS 'Znachenie polya `public.priorities.name` dolzhno byt unikalnym.';
COMMENT ON CONSTRAINT uk_priorities_level ON public.priorities IS 'Znachenie polya `public.priorities.level` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.projects(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(255) COLLATE pg_catalog."default" NOT NULL,
key character varying(50) COLLATE pg_catalog."default" NOT NULL,
description text COLLATE pg_catalog."default",
lead_id bigint NOT NULL,
default_workflow_id bigint,
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT projects_pkey PRIMARY KEY (id),
CONSTRAINT uk_projects_key UNIQUE (key),
CONSTRAINT uk_projects_name UNIQUE (name));

COMMENT ON TABLE public.projects IS 'Predstavlyaet soboy otdelnye proekty, v ramkakh kotorykh vedutsya zadachi. Kazhdyy proekt imeet svoego rukovoditelya, unikalnyy klyuch i nabor zadach.';

COMMENT ON COLUMN public.projects.id IS 'Unikalnyy identifikator proekta.';
COMMENT ON COLUMN public.projects.name IS 'Polnoe nazvanie proekta.';
COMMENT ON COLUMN public.projects.key IS 'Unikalnyy korotkiy klyuch proekta (prefiks, ispolzuemyy v klyuchakh zadach, naprimer, "PROJ").';
COMMENT ON COLUMN public.projects.description IS 'Opisanie proekta.';
COMMENT ON COLUMN public.projects.lead_id IS 'Ssylka na polzovatelya, kotoryy yavlyaetsya rukovoditelem proekta.';
COMMENT ON COLUMN public.projects.default_workflow_id IS 'Ssylka na rabochiy protsess, kotoryy budet ispolzovatsya po umolchaniyu dlya zadach v etom proekte, esli ne ukazan bolee spetsificheskiy.';
COMMENT ON COLUMN public.projects.created_at IS 'Vremennaya metka sozdaniya.';
COMMENT ON COLUMN public.projects.updated_at IS 'Vremennaya metka poslednego obnovleniya.';

COMMENT ON CONSTRAINT uk_projects_key ON public.projects IS 'Znachenie polya `public.projects.key` dolzhno byt unikalnym.';
COMMENT ON CONSTRAINT uk_projects_name ON public.projects IS 'Znachenie polya `public.projects.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.issue_statuses(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(50) COLLATE pg_catalog."default" NOT NULL,
description text COLLATE pg_catalog."default",
CONSTRAINT issue_statuses_pkey PRIMARY KEY (id),
CONSTRAINT uk_issue_statuses_name UNIQUE (name));

COMMENT ON TABLE public.issue_statuses IS 'Opredelyaet razlichnye sostoyaniya, cherez kotorye mozhet prokhodit zadacha v svoem zhiznennom tsikle (naprimer: Open, In Progress, Resolved). Statusy yavlyayutsya chastyu rabochego protsessa.';

COMMENT ON COLUMN public.issue_statuses.id IS 'Unikalnyy identifikator statusa.';
COMMENT ON COLUMN public.issue_statuses.name IS 'Nazvanie statusa.';
COMMENT ON COLUMN public.issue_statuses.description IS 'Opisanie statusa.';

COMMENT ON CONSTRAINT uk_issue_statuses_name ON public.issue_statuses IS 'Znachenie polya `public.issue_statuses.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.users(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
email character varying(255) COLLATE pg_catalog."default" NOT NULL,
username character varying(255) COLLATE pg_catalog."default" NOT NULL,
password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
CONSTRAINT users_pkey PRIMARY KEY (id),
CONSTRAINT uk_users_email UNIQUE (email),
CONSTRAINT uk_users_username UNIQUE (username));

COMMENT ON TABLE public.users IS 'Khranit informatsiyu obo vsekh zaregistrirovannykh polzovatelyakh sistemy. Eto tsentralnaya sushchnost, k kotoroy privyazany mnogie drugie deystviya i obekty.';

COMMENT ON COLUMN public.users.id IS 'Unikalnyy identifikator polzovatelya.';
COMMENT ON COLUMN public.users.email IS 'Elektronnaya pochta polzovatelya (ispolzuetsya dlya vkhoda i uvedomleniy).';
COMMENT ON COLUMN public.users.username IS 'Unikalnoe imya polzovatelya.';
COMMENT ON COLUMN public.users.password_hash IS 'Khesh parolya polzovatelya (vazhno dlya bezopasnosti, khranyatsya ne sami paroli, a ikh kheshi).';

COMMENT ON CONSTRAINT uk_users_email ON public.users IS 'Znachenie polya `public.users.email` dolzhno byt unikalnym.';
COMMENT ON CONSTRAINT uk_users_username ON public.users IS 'Znachenie polya `public.users.username` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.workflow_statuses(
workflow_id bigint NOT NULL,
status_id bigint NOT NULL,
CONSTRAINT workflow_statuses_pkey PRIMARY KEY (workflow_id, status_id));

COMMENT ON TABLE public.workflow_statuses IS 'Svyazuyushchaya tablitsa (mnogie-ko-mnogim), kotoraya opredelyaet, kakie statusy vklyucheny v konkretnyy rabochiy protsess.';

COMMENT ON COLUMN public.workflow_statuses.workflow_id IS 'Ssylka na rabochiy protsess.';
COMMENT ON COLUMN public.workflow_statuses.status_id IS 'Ssylka na status zadachi.';

CREATE TABLE IF NOT EXISTS public.workflow_transitions(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(255) COLLATE pg_catalog."default" NOT NULL,
from_status_id bigint NOT NULL,
to_status_id bigint NOT NULL,
workflow_id bigint NOT NULL,
CONSTRAINT workflow_transitions_pkey PRIMARY KEY (id),
CONSTRAINT uk_workflow_transitions_unique_pair UNIQUE (workflow_id, name, from_status_id, to_status_id));

COMMENT ON TABLE public.workflow_transitions IS 'Opredelyaet dopustimye perekhody mezhdu statusami vnutri odnogo rabochego protsessa. Naprimer, iz statusa "Open" mozhno pereyti v "In Progress", no ne napryamuyu v "Closed".';

COMMENT ON COLUMN public.workflow_transitions.id IS 'Unikalnyy identifikator perekhoda.';
COMMENT ON COLUMN public.workflow_transitions.name IS 'Nazvanie perekhoda (naprimer, "Start work", "Resolve issue").';
COMMENT ON COLUMN public.workflow_transitions.from_status_id IS 'Ssylka na iskhodnyy status.';
COMMENT ON COLUMN public.workflow_transitions.to_status_id IS 'Ssylka na tselevoy status.';
COMMENT ON COLUMN public.workflow_transitions.workflow_id IS 'Ssylka na rabochiy protsess, k kotoromu otnositsya etot perekhod.';

COMMENT ON CONSTRAINT uk_workflow_transitions_unique_pair1 ON public.workflow_transitions IS 'Znachenie sochetaniya poley `public.workflow_transitions.workflow_id` i `public.workflow_transitions.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.workflows(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
is_default boolean NOT NULL DEFAULT false,
name character varying(255) COLLATE pg_catalog."default" NOT NULL,
CONSTRAINT workflows_pkey PRIMARY KEY (id),
CONSTRAINT uk_workflows_name UNIQUE (name));

COMMENT ON TABLE public.workflows IS 'Kazhdyy rabochiy protsess opisyvaet zhienennyy tsikl zadachi.';

COMMENT ON COLUMN public.workflows.id IS 'Unikalnyy identifikator rabochego protsessa.';
COMMENT ON COLUMN public.workflows.is_default IS 'Flag, ukazyvayushchiy, yavlyaetsya li etot rabochiy protsess po umolchaniyu dlya sistemy ili opredelennykh tipov zadach.';
COMMENT ON COLUMN public.workflows.name IS 'Nazvanie rabochego protsessa.';

COMMENT ON CONSTRAINT uk_workflows_name ON public.workflows IS 'Znachenie polya `public.workflows.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.comments(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
issue_id bigint NOT NULL,
author_id bigint NOT NULL,
content text COLLATE pg_catalog."default" NOT NULL,
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT comments_pkey PRIMARY KEY (id));

COMMENT ON TABLE public.comments IS 'Khranit kommentarii, dobavlennye k zadacham. Pozvolyaet polzovatelyam obsuzhdat i utochnyat detali zadach.';

COMMENT ON COLUMN public.comments.id IS 'Unikalnyy identifikator kommentariya.';
COMMENT ON COLUMN public.comments.issue_id IS 'Ssylka na zadachu, k kotoroy otnositsya kommentariy.';
COMMENT ON COLUMN public.comments.author_id IS 'Ssylka na polzovatelya, kotoryy ostavil kommentariy.';
COMMENT ON COLUMN public.comments.content IS 'Tekst kommentariya.';
COMMENT ON COLUMN public.comments.created_at IS 'Vremennaya metka sozdaniya kommentariya.';
COMMENT ON COLUMN public.comments.updated_at IS 'Vremennaya metka poslednego obnovleniya kommentariya.';

CREATE TABLE IF NOT EXISTS public.activity_log(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
issue_id bigint NOT NULL,
user_id bigint,
action_type_id bigint NOT NULL,
field_name character varying(100) COLLATE pg_catalog."default",
old_value text COLLATE pg_catalog."default",
new_value text COLLATE pg_catalog."default",
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT activity_log_pkey PRIMARY KEY (id));

COMMENT ON TABLE public.activity_log IS 'Zapisyvaet vse znachimye izmeneniya i deystviya, proiskhodyashchie s zadachami (naprimer, izmenenie statusa, naznachenie ispolnitelya, obnovlenie opisaniya, dobavlenie kommentariya/vlozheniya). Pozvolyaet prosmatrivat istoriyu izmeneniy zadachi.';

COMMENT ON COLUMN public.activity_log.id IS 'Unikalnyy identifikator zapisi zhurnala.';
COMMENT ON COLUMN public.activity_log.issue_id IS 'Ssylka na zadachu, k kotoroy otnositsya zapis.';
COMMENT ON COLUMN public.activity_log.user_id IS 'Ssylka na polzovatelya, kotoryy vypolnil deystvie';
COMMENT ON COLUMN public.activity_log.action_type_id IS 'Ssylka na tip deystviya, kotoroe proiskhodit dlya zadachi';
COMMENT ON COLUMN public.activity_log.field_name IS 'Imya polya, kotoroe bylo izmeneno (esli primenimo).';
COMMENT ON COLUMN public.activity_log.old_value IS 'Predydushchee znachenie polya (esli primenimo).';
COMMENT ON COLUMN public.activity_log.new_value IS 'Novoe znachenie polya (esli primenimo).';
COMMENT ON COLUMN public.activity_log.created_at IS 'Vremennaya metka sozdaniya.';

CREATE TABLE IF NOT EXISTS public.action_types(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(100) COLLATE pg_catalog."default" NOT NULL,
CONSTRAINT action_types_pkey PRIMARY KEY (id),
CONSTRAINT action_types_name UNIQUE (name));

COMMENT ON TABLE public.action_types IS 'Khranit vse tipy deystviy, proiskhodyashchie zadachami (naprimer, izmenenie statusa, naznachenie ispolnitelya, obnovlenie opisaniya, dobavlenie kommentariya/vlozheniya).';

COMMENT ON COLUMN public.action_types.id IS 'Unikalnyy identifikator tipa deystviya.';
COMMENT ON COLUMN public.action_types.name IS 'Tip deystviya (naprimer, "STATUS_CHANGE", "ASSIGNED", "COMMENTED").';

CREATE TABLE IF NOT EXISTS public.attachments(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
issue_id bigint NOT NULL,
uploader_id bigint NOT NULL,
file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
file_type_id bigint NOT NULL,
file_size_bytes bigint NOT NULL,
storage_path character varying(512) COLLATE pg_catalog."default" NOT NULL,
description text COLLATE pg_catalog."default",
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT attachments_pkey PRIMARY KEY (id));

COMMENT ON TABLE public.attachments IS 'Khranit metadannye faylov, prikreplennykh k zadacham. Sami fayly obychno khranyatsya v faylovoy sisteme ili oblachnom khranilishche, v BD — tolko ssylki na nikh.';

COMMENT ON COLUMN public.attachments.id IS 'Unikalnyy identifikator vlozheniya.';
COMMENT ON COLUMN public.attachments.issue_id IS 'Ssylka na zadachu, k kotoroy prikreplen fayl.';
COMMENT ON COLUMN public.attachments.uploader_id IS 'Ssylka na polzovatelya, kotoryy zagruzil fayl.';
COMMENT ON COLUMN public.attachments.file_name IS 'Imya fayla.';
COMMENT ON COLUMN public.attachments.file_type_id IS 'Ssylka na tip fayla iz tablitsy `file_types`.';
COMMENT ON COLUMN public.attachments.file_size_bytes IS 'Razmer fayla v baytakh.';
COMMENT ON COLUMN public.attachments.storage_path IS 'Put ili URL, ukazyvayushchiy na fakticheskoe mestopolozhenie fayla.';
COMMENT ON COLUMN public.attachments.created_at IS 'Vremennaya metka zagruzki fayla.';
COMMENT ON COLUMN public.attachments.description IS 'Opisanie fayla.';

CREATE TABLE IF NOT EXISTS public.file_types(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
extension character varying(20) COLLATE pg_catalog."default" NOT NULL,
mime_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
CONSTRAINT file_types_pkey PRIMARY KEY (id),
CONSTRAINT uk_file_types_extension UNIQUE (extension),
CONSTRAINT uk_file_types_mime_type UNIQUE (mime_type));

COMMENT ON TABLE public.file_types IS 'Spravochnik dlya khraneniya izvestnykh tipov faylov po ikh rasshireniyam i MIME-tipam. Ispolzuetsya dlya klassifikatsii vlozheniy.';

COMMENT ON COLUMN public.file_types.id IS 'Unikalnyy identifikator tipa fayla.';
COMMENT ON COLUMN public.file_types.extension IS 'Rasshirenie fayla (naprimer, "png", "pdf").';
COMMENT ON COLUMN public.file_types.mime_type IS 'MIME-tip fayla (naprimer, "image/png", "application/pdf").';

COMMENT ON CONSTRAINT uk_file_types_extension ON public.file_types IS 'Znachenie polya `public.file_types.extension` dolzhno byt unikalnym.';
COMMENT ON CONSTRAINT uk_file_types_mime_type ON public.file_types IS 'Znachenie polya `public.file_types.mime_type` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.issue_link_types(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(100) COLLATE pg_catalog."default" NOT NULL,
inward_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
CONSTRAINT issue_link_types_pkey PRIMARY KEY (id),
CONSTRAINT uk_issue_link_types_name UNIQUE (name),
CONSTRAINT uk_issue_link_types_inward_name UNIQUE (inward_name));

COMMENT ON TABLE public.issue_link_types IS 'Opredelyaet razlichnye vidy svyazey mezhdu zadachami (naprimer, "blocks" (blokiruet), "relates to" (svyazana), "duplicates" (dubliruet)). Pozvolyaet stroit graf zavisimostey mezhdu zadachami.';

COMMENT ON COLUMN public.issue_link_types.id IS 'Unikalnyy identifikator tipa svyazi.';
COMMENT ON COLUMN public.issue_link_types.name IS 'Pryamoe nazvanie svyazi (naprimer: "Blocks", "Clones", "Relates to").';
COMMENT ON COLUMN public.issue_link_types.inward_name IS 'Obratnoe nazvanie svyazi (naprimer: "is blocked by", "is cloned by", "is related to").';

COMMENT ON CONSTRAINT uk_issue_link_types_name ON public.issue_link_types IS 'Znachenie polya `public.issue_link_types.name` dolzhno byt unikalnym.';
COMMENT ON CONSTRAINT uk_issue_link_types_inward_name ON public.issue_link_types IS 'Znachenie polya `public.issue_link_types.inward_name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.issue_links(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
source_issue_id bigint NOT NULL,
target_issue_id bigint NOT NULL,
link_type_id bigint NOT NULL,
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT issue_links_pkey PRIMARY KEY (id),
CONSTRAINT uk_issue_links_unique_pair1 UNIQUE (source_issue_id, target_issue_id, link_type_id));

COMMENT ON TABLE public.issue_links IS 'Khranit konkretnye svyazi mezhdu dvumya zadachami, ispolzuya opredelennyy tip svyazi.';

COMMENT ON COLUMN public.issue_links.id IS 'Unikalnyy identifikator svyazi.';
COMMENT ON COLUMN public.issue_links.source_issue_id IS 'Ssylka na iskhodnuyu zadachu.';
COMMENT ON COLUMN public.issue_links.target_issue_id IS 'Ssylka na tselevuyu zadachu.';
COMMENT ON COLUMN public.issue_links.link_type_id IS 'Ssylka na tip svyazi iz tablitsy `issue_link_types`.';
COMMENT ON COLUMN public.issue_links.created_at IS 'Vremennaya metka sozdaniya svyazi.';

COMMENT ON CONSTRAINT uk_issue_links_unique_pair1 ON public.issue_links IS 'Znachenie sochetaniya poley `public.issue_links.source_issue_id`, `public.issue_links.target_issue_id` i `public.issue_links.link_type_id` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.issue_watchers(
issue_id bigint NOT NULL,
user_id bigint NOT NULL,
CONSTRAINT issue_watchers_pkey PRIMARY KEY (issue_id, user_id));

COMMENT ON TABLE public.issue_watchers IS 'Khranit spisok polzovateley, kotorye "nablyudayut" za opredelennoy zadachey i khotyat poluchat uvedomleniya izmeneniy.';

COMMENT ON COLUMN public.issue_watchers.issue_id IS 'Ssylka na zadachu.';
COMMENT ON COLUMN public.issue_watchers.user_id IS 'Ssylka na polzovatelya-nablyudatelya.';

CREATE TABLE IF NOT EXISTS public.roles(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(100) COLLATE pg_catalog."default" NOT NULL,
description text COLLATE pg_catalog."default",
is_system_role boolean NOT NULL DEFAULT FALSE,
CONSTRAINT roles_pkey PRIMARY KEY (id),
CONSTRAINT uk_roles_name UNIQUE (name));

COMMENT ON TABLE public.roles IS 'Opredelyaet razlichnye roli v sisteme (naprimer, "Administrator" (Administrator), "Developer" (Razrabotchik), "Viewer" (Nablyudatel)). Roli ispolzuyutsya dlya gruppirovki razresheniy.';

COMMENT ON COLUMN public.roles.id IS 'Unikalnyy identifikator roli.';
COMMENT ON COLUMN public.roles.name IS 'Nazvanie roli (naprimer: "Administrator", "Developer", "Viewer").';
COMMENT ON COLUMN public.roles.description IS 'Opisanie roli.';
COMMENT ON COLUMN public.roles.is_system_role IS 'Flag, ukazyvayushchiy, yavlyaetsya li rol vstroennoy/sistemnoy.';

COMMENT ON CONSTRAINT uk_roles_name ON public.roles IS 'Znachenie polya `public.roles.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.permissions(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(100) COLLATE pg_catalog."default" NOT NULL,
description text COLLATE pg_catalog."default",
CONSTRAINT permissions_pkey PRIMARY KEY (id),
CONSTRAINT uk_permissions_name UNIQUE (name));

COMMENT ON TABLE public.permissions IS 'Opredelyaet atomarnye razresheniya, kotorye mogut byt predostavleny rolyam (naprimer, "BROWSE_PROJECTS" (prosmotr proektov), "EDIT_ISSUES" (redaktirovanie zadach), "CREATE_ISSUES" (sozdanie zadach)).';

COMMENT ON COLUMN public.permissions.id IS 'Unikalnyy identifikator razresheniya.';
COMMENT ON COLUMN public.permissions.name IS 'Nazvanie razresheniya (naprimer: "BROWSE_PROJECTS", "EDIT_ISSUES", "CREATE_ISSUES", "DELETE_ISSUES").';
COMMENT ON COLUMN public.permissions.description IS 'Opisanie razresheniya.';

COMMENT ON CONSTRAINT uk_permissions_name ON public.permissions IS 'Znachenie polya `public.permissions.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.role_permissions(
role_id bigint NOT NULL,
permission_id bigint NOT NULL,
CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id));

COMMENT ON TABLE public.role_permissions IS 'Svyazuyushchaya tablitsa (mnogie-ko-mnogim), kotoraya sopostavlyaet roli s razresheniyami. Opredelyaet, kakie razresheniya vkhodyat v kazhduyu rol.';

COMMENT ON COLUMN public.role_permissions.role_id IS 'Ssylka na rol.';
COMMENT ON COLUMN public.role_permissions.permission_id IS 'Ssylka na razreshenie.';

CREATE TABLE IF NOT EXISTS public.project_members(
project_id bigint NOT NULL,
group_id bigint NOT NULL,
role_id bigint NOT NULL,
CONSTRAINT project_members_pkey PRIMARY KEY (project_id, group_id, role_id));

COMMENT ON TABLE public.project_members IS 'Opredelyaet, kakie gruppy imeyut kakie roli v konkretnykh proektakh. Cherez eto ustanavlivayutsya prava dostupa k proektu dlya grupp polzovateley.';

COMMENT ON COLUMN public.project_members.project_id IS 'Ssylka na proekt.';
COMMENT ON COLUMN public.project_members.group_id IS 'Ssylka na gruppu, kotoroy naznachena rol v etom proekte.';
COMMENT ON COLUMN public.project_members.role_id IS 'Ssylka na rol, kotoruyu eta gruppa imeet v proekte.';

CREATE TABLE IF NOT EXISTS public.project_issue_type_workflow_defaults(
project_id bigint NOT NULL,
issue_type_id bigint NOT NULL,
workflow_id bigint NOT NULL,
CONSTRAINT project_issue_type_workflow_defaults_pkey PRIMARY KEY (project_id, issue_type_id, workflow_id));

COMMENT ON TABLE public.project_issue_type_workflow_defaults IS 'Pozvolyaet opredelit, kakoy rabochiy protsess dolzhen ispolzovatsya po umolchaniyu dlya opredelennogo tipa zadach v ramkakh konkretnogo proekta. Eto pozvolyaet proektam imet kastomizirovannye rabochie protsessy dlya raznykh tipov zadach.';

COMMENT ON COLUMN public.project_issue_type_workflow_defaults.project_id IS 'Ssylka na proekt.';
COMMENT ON COLUMN public.project_issue_type_workflow_defaults.issue_type_id IS 'Ssylka na tip zadachi.';
COMMENT ON COLUMN public.project_issue_type_workflow_defaults.workflow_id IS 'Ssylka na rabochiy protsess, kotoryy yavlyaetsya umolchaniem dlya etoy pary.';

CREATE TABLE IF NOT EXISTS public.notification_templates(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(100) COLLATE pg_catalog."default" NOT NULL,
subject_template text COLLATE pg_catalog."default",
body_template text COLLATE pg_catalog."default" NOT NULL,
template_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
is_active boolean NOT NULL DEFAULT TRUE,
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
CONSTRAINT uk_notification_templates_name UNIQUE (name));

COMMENT ON TABLE public.notification_templates IS 'Khranit parametrizovannye shablony dlya razlichnykh tipov uvedomleniy (naprimer, dlya elektronnykh pisem, vnutrisistemnykh soobshcheniy). Eto pozvolyaet legko izmenyat tekst uvedomleniy bez izmeneniya koda.';

COMMENT ON COLUMN public.notification_templates.id IS 'Unikalnyy identifikator shablona.';
COMMENT ON COLUMN public.notification_templates.name IS 'Unikalnoe imya shablona (dlya identifikatsii v kode).';
COMMENT ON COLUMN public.notification_templates.subject_template IS 'Shablon dlya temy uvedomleniya (esli primenimo, naprimer, dlya email).';
COMMENT ON COLUMN public.notification_templates.body_template IS 'Osnovnoy tekst shablona uvedomleniya (mozhet byt HTML ili prostoy tekst).';
COMMENT ON COLUMN public.notification_templates.template_type IS 'Tip kanala uvedomleniya (naprimer, "EMAIL", "IN_APP", "SLACK").';
COMMENT ON COLUMN public.notification_templates.is_active IS 'Flag aktivnosti shablona.';
COMMENT ON COLUMN public.notification_templates.created_at IS 'Vremennaya metka sozdaniya shablona.';
COMMENT ON COLUMN public.notification_templates.updated_at IS 'Vremennaya metka poslednego vneseniya izmeneniy v shablon.';

COMMENT ON CONSTRAINT uk_notification_templates_name ON public.notification_templates IS 'Znachenie polya `public.notification_templates.name` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.user_notification_settings(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
user_id bigint NOT NULL,
notification_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
is_enabled boolean NOT NULL DEFAULT TRUE,
CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id),
CONSTRAINT uk_user_notification_settings_unique UNIQUE (user_id, notification_type));

COMMENT ON TABLE public.user_notification_settings IS 'Pozvolyaet kazhdomu polzovatelyu nastraivat, kakie tipy uvedomleniy on khochet poluchat i po kakim kanalam.';

COMMENT ON COLUMN public.user_notification_settings.id IS 'Unikalnyy identifikator nastroyki.';
COMMENT ON COLUMN public.user_notification_settings.user_id IS 'Ssylka na polzovatelya.';
COMMENT ON COLUMN public.user_notification_settings.notification_type IS 'Tip uvedomleniya (naprimer, "ISSUE_CREATED_EMAIL", "COMMENT_ADDED_IN_APP"), dolzhen sootvetstvovat logike prilozheniya.';
COMMENT ON COLUMN public.user_notification_settings.is_enabled IS 'Vklyuchena li dannaya nastroyka dlya polzovatelya.';

COMMENT ON CONSTRAINT uk_user_notification_settings_unique ON public.user_notification_settings IS 'Znachenie sochetaniya poley `public.user_notification_settings.user_id` i `public.user_notification_settings.notification_type` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.notification_queue(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
recipient_user_id bigint,
recipient_email character varying(255) COLLATE pg_catalog."default",
template_id bigint,
issue_id bigint,
project_id bigint,
payload jsonb,
status_id bigint NOT NULL,
sent_at timestamp(6) without time zone,
failed_attempts integer NOT NULL DEFAULT 0,
created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT notification_queue_pkey PRIMARY KEY (id));

COMMENT ON TABLE public.notification_queue IS 'Ispolzuetsya dlya asinkhronnoy obrabotki i otpravki uvedomleniy. Prilozhenie dobavlyaet uvedomleniya v etu ochered, a otdelnyy fonovyy protsess zabiraet ikh i otpravlyaet, chto predotvrashchaet blokirovku osnovnogo potoka vypolneniya.';

COMMENT ON COLUMN public.notification_queue.id IS 'Unikalnyy identifikator zapisi v ocheredi.';
COMMENT ON COLUMN public.notification_queue.recipient_user_id IS 'Ssylka na polzovatelya-poluchatelya (esli izvesten).';
COMMENT ON COLUMN public.notification_queue.recipient_email IS 'Pryamoy adres elektronnoy pochty (esli poluchatel ne zaregistrirovannyy polzovatel ili nuzhno otpravit na vneshniy adres).';
COMMENT ON COLUMN public.notification_queue.template_id IS 'Ssylka na shablon uvedomleniya, kotoryy nuzhno ispolzovat.';
COMMENT ON COLUMN public.notification_queue.issue_id IS 'Neobyazatelnaya ssylka na zadachu, esli uvedomlenie svyazano s nim (dlya konteksta).';
COMMENT ON COLUMN public.notification_queue.project_id IS 'Neobyazatelnaya ssylka na proekt, esli uvedomlenie svyazano s nim (dlya konteksta).';
COMMENT ON COLUMN public.notification_queue.payload IS 'JSONB-pole dlya khraneniya vsekh peremennykh dannykh, kotorye budut vstavleny v shablon (naprimer, imya zadachi, staryy/novyy status).';
COMMENT ON COLUMN public.notification_queue.status_id IS 'Ssylka na status obrabotki uvedomleniya.';
COMMENT ON COLUMN public.notification_queue.sent_at IS 'Vremennaya metka otpravki.';
COMMENT ON COLUMN public.notification_queue.failed_attempts IS 'Kolichestvo neudachnykh popytok otpravki.';
COMMENT ON COLUMN public.notification_queue.created_at IS 'Vremennaya metka sozdaniya zapisi v ocheredi.';

CREATE TABLE IF NOT EXISTS public.notification_statuses(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(20) COLLATE pg_catalog."default" NOT NULL,
is_default boolean NOT NULL DEFAULT false,
CONSTRAINT notification_statuses_pkey PRIMARY KEY (id));

COMMENT ON TABLE public.notification_statuses IS 'Opredelyaet perechen statusov obrabotki ocheredi uvedomleniy.';

COMMENT ON COLUMN public.notification_statuses.id IS 'Unikalnyy identifikator statusa uvedomleniya.';
COMMENT ON COLUMN public.notification_statuses.name IS 'Naimenovanie statusa obrabotki uvedomleniya (naprimer, "PENDING" (ozhidaet), "SENT" (otpravleno), "FAILED" (oshibka)).';
COMMENT ON COLUMN public.notification_statuses.is_default IS 'Flag, ukazyvayushchiy, yavlyaetsya li etot status po umolchaniyu dlya ocheredi obrabotki uvedomleniy.';

CREATE TABLE IF NOT EXISTS public.groups(
id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
name character varying(100) COLLATE pg_catalog."default" NOT NULL,
description text COLLATE pg_catalog."default",
is_system_group boolean NOT NULL DEFAULT FALSE,
CONSTRAINT groups_pkey PRIMARY KEY (id),
CONSTRAINT uk_groups_name_is_system_group UNIQUE (name, is_system_group));

COMMENT ON TABLE public.groups IS 'Pozvolyaet obedinyat polzovateley v logicheskie gruppy (naprimer, "Komanda razrabotki", "Komanda QA", "Rukovoditeli"). Uproshchaet upravlenie dostupom k proektam i massovoe naznachenie prav.';

COMMENT ON COLUMN public.groups.id IS 'Unikalnyy identifikator gruppy.';
COMMENT ON COLUMN public.groups.name IS 'Nazvanie gruppy (naprimer: "Developers", "QA Team", "Admins").';
COMMENT ON COLUMN public.groups.description IS 'Opisanie gruppy.';
COMMENT ON COLUMN public.groups.is_system_group IS 'Flag dlya sistemnykh/vstroennykh grupp.';

COMMENT ON CONSTRAINT uk_groups_name_is_system_group ON public.groups IS 'Sochetanie znacheniy polya `public.groups.name` i `public.groups.is_system_group` dolzhno byt unikalnym.';

CREATE TABLE IF NOT EXISTS public.user_groups(
user_id bigint NOT NULL,
group_id bigint NOT NULL,
CONSTRAINT user_groups_pkey PRIMARY KEY (user_id, group_id));

COMMENT ON TABLE public.user_groups IS 'Svyazuyushchaya tablitsa (mnogie-ko-mnogim), kotoraya ukazyvaet, kakie polzovateli vkhodyat v kakie gruppy.';

COMMENT ON COLUMN public.user_groups.user_id IS 'Ssylka na polzovatelya.';
COMMENT ON COLUMN public.user_groups.group_id IS 'Ssylka na gruppu polzovateley.';


-- ***********************************************************************************
--                              FOREIGN KEYS
-- ***********************************************************************************
ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_assignee FOREIGN KEY (assignee_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_issue_type FOREIGN KEY (issue_type_id)
    REFERENCES public.issue_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_reporter FOREIGN KEY (reporter_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_priority FOREIGN KEY (priority_id)
    REFERENCES public.priorities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_status FOREIGN KEY (status_id)
    REFERENCES public.issue_statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_workflow FOREIGN KEY (workflow_id)
    REFERENCES public.workflows (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.issues
    ADD CONSTRAINT fk_issues_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT fk_issues_assignee ON public.issues IS 'Nelzya udalit polzovatelya, kotoromu naznachena zadacha.';
COMMENT ON CONSTRAINT fk_issues_issue_type ON public.issues IS 'Nelzya udalit tip zadachi, kotoryy privyazan k zadacham.';
COMMENT ON CONSTRAINT fk_issues_reporter ON public.issues IS 'Nelzya udalit polzovatelya, kotoryy yavlyaetsya avtorom zadachi.';
COMMENT ON CONSTRAINT fk_issues_priority ON public.issues IS 'Nelzya udalit prioritet, kotoryy privyazan k zadache.';
COMMENT ON CONSTRAINT fk_issues_status ON public.issues IS 'Nelzya udalit status, kotoryy privyazan k zadache.';
COMMENT ON CONSTRAINT fk_issues_workflow ON public.issues IS 'Nelzya udalit rabochiy protsess, esli ego znachenie v zadache.';
COMMENT ON CONSTRAINT fk_issues_project ON public.issues IS 'Esli udalyaetsya proekt, udalyayutsya vse ego zadachi.';

ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_projects_lead FOREIGN KEY (lead_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_projects_default_workflow FOREIGN KEY (default_workflow_id)
    REFERENCES public.workflows (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_projects_lead ON public.projects IS 'Nelzya udalit polzovatelya yavlyayushchegosya rukovoditelem proekta.';
COMMENT ON CONSTRAINT fk_projects_default_workflow ON public.projects IS 'Nelzya udalit rabochiy protsess, esli ego znachenie v proekte.';

ALTER TABLE IF EXISTS public.workflow_statuses
    ADD CONSTRAINT fk_workflow_statuses_status FOREIGN KEY (status_id)
    REFERENCES public.issue_statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_statuses
    ADD CONSTRAINT fk_workflow_statuses_workflow FOREIGN KEY (workflow_id)
    REFERENCES public.workflows (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_workflow_statuses_status ON public.workflow_statuses IS 'Nelzya udalit status zadachi, esli est svyazannye statusy rabochego protsessa.';
COMMENT ON CONSTRAINT fk_workflow_statuses_workflow ON public.workflow_statuses IS 'Nelzya udalit rabochiy protsess, esli est svyazannye statusy rabochego protsessa.';

ALTER TABLE IF EXISTS public.workflow_transitions
    ADD CONSTRAINT fk_workflow_transitions_workflow FOREIGN KEY (workflow_id)
    REFERENCES public.workflows (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_transitions
    ADD CONSTRAINT fk_workflow_transitions_from_status FOREIGN KEY (from_status_id)
    REFERENCES public.issue_statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.workflow_transitions
    ADD CONSTRAINT fk_workflow_transitions_to_status FOREIGN KEY (to_status_id)
    REFERENCES public.issue_statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_workflow_transitions_workflow ON public.workflow_transitions IS 'Nelzya udalit rabochiy protsess, esli est svyazannye perekhody statusa v rabochem protsesse.';
COMMENT ON CONSTRAINT fk_workflow_transitions_from_status ON public.workflow_transitions IS 'Nelzya udalit status zadachi, esli est svyazannye perekhody statusa v rabochem protsesse.';
COMMENT ON CONSTRAINT fk_workflow_transitions_to_status ON public.workflow_transitions IS 'Nelzya udalit status zadachi, esli est svyazannye perekhody statusa v rabochem protsesse.';

ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comments_issue FOREIGN KEY (issue_id)
    REFERENCES public.issues (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comments_author FOREIGN KEY (author_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_comments_issue ON public.comments IS 'Esli udalyaetsya zadacha, udalyayutsya vse svyazannye kommentarii.';
COMMENT ON CONSTRAINT fk_comments_author ON public.comments IS 'Nelzya udalit polzovatelya yavlyayushchegosya avtorom kommentariya k zadache.';

ALTER TABLE IF EXISTS public.activity_log
    ADD CONSTRAINT fk_activity_log_issue FOREIGN KEY (issue_id)
    REFERENCES public.issues (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.activity_log
    ADD CONSTRAINT fk_activity_log_action_type FOREIGN KEY (action_type_id)
    REFERENCES public.action_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.activity_log
    ADD CONSTRAINT fk_activity_log_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_activity_log_issue ON public.activity_log IS 'Esli udalyaetsya zadacha, udalyayutsya vse svyazannye aktivnosti.';
COMMENT ON CONSTRAINT fk_activity_log_action_type ON public.activity_log IS 'Nelzya udalit tip deystviya, u kotorogo est osushchestvlennaya aktivnost.';
COMMENT ON CONSTRAINT fk_activity_log_user ON public.activity_log IS 'Nelzya udalit polzovatelya, u kotorogo est osushchestvlennaya aktivnost.';

ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT fk_attachments_issue FOREIGN KEY (issue_id)
    REFERENCES public.issues (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT fk_attachments_uploader FOREIGN KEY (uploader_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT fk_attachments_file_type FOREIGN KEY (file_type_id)
    REFERENCES public.file_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_attachments_issue ON public.attachments IS 'Esli udalyaetsya zadacha, udalyayutsya vse svyazannye dokumenty.';
COMMENT ON CONSTRAINT fk_attachments_uploader ON public.attachments IS 'Nelzya udalit polzovatelya, zagruzivshego dokument.';
COMMENT ON CONSTRAINT fk_attachments_file_type ON public.attachments IS 'Nelzya udalit tip fayla, esli est svyazannyy dokument.';

ALTER TABLE IF EXISTS public.issue_links
    ADD CONSTRAINT fk_issue_links_source_issue FOREIGN KEY (source_issue_id)
    REFERENCES public.issues (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.issue_links
    ADD CONSTRAINT fk_issue_links_target_issue FOREIGN KEY (target_issue_id)
    REFERENCES public.issues (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.issue_links
    ADD CONSTRAINT fk_issue_links_type FOREIGN KEY (link_type_id)
    REFERENCES public.issue_link_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_issue_links_source_issue ON public.issue_links IS 'Esli udalyaetsya zadacha, udalyayutsya vse svyazi zadach.';
COMMENT ON CONSTRAINT fk_issue_links_target_issue ON public.issue_links IS 'Esli udalyaetsya zadacha, udalyayutsya vse svyazi zadach.';
COMMENT ON CONSTRAINT fk_issue_links_type ON public.issue_links IS 'Nelzya udalit tip svyazi zadachi, poka uchastvuet v opredelenii svyazey zadach.';

ALTER TABLE IF EXISTS public.issue_watchers
    ADD CONSTRAINT fk_issue_watchers_issue FOREIGN KEY (issue_id)
    REFERENCES public.issues (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.issue_watchers
    ADD CONSTRAINT fk_issue_watchers_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_issue_watchers_issue ON public.issue_watchers IS 'Esli udalyaetsya zadacha, udalyayutsya vse svyazannye nablyudateli zadach.';
COMMENT ON CONSTRAINT fk_issue_watchers_user ON public.issue_watchers IS 'Nelzya udalit polzovatelya, esli on yavlyaetsya nablyudatelem zadach.';

ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_role_permissions_role ON public.role_permissions IS 'Nelzya udalit rol, esli est svyazannye dostupy po roli.';
COMMENT ON CONSTRAINT fk_role_permissions_permission ON public.role_permissions IS 'Nelzya udalit dostup, esli est svyazannye roli po dostupu.';

ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_project_members_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_project_members_group FOREIGN KEY (group_id)
    REFERENCES public.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_project_members_role FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_project_members_project ON public.project_members IS 'Esli udalyaetsya proekt, udalyayutsya vse svyazannye chleny proekta.';
COMMENT ON CONSTRAINT fk_project_members_group ON public.project_members IS 'Nelzya udalit gruppu polzovateley, esli est svyazannye chleny proekta.';
COMMENT ON CONSTRAINT fk_project_members_role ON public.project_members IS 'Nelzya udalit rol, esli est svyazannye chleny proekta.';

ALTER TABLE IF EXISTS public.project_issue_type_workflow_defaults
    ADD CONSTRAINT fk_pitwd_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.project_issue_type_workflow_defaults
    ADD CONSTRAINT fk_pitwd_issue_type FOREIGN KEY (issue_type_id)
    REFERENCES public.issue_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.project_issue_type_workflow_defaults
    ADD CONSTRAINT fk_pitwd_workflow FOREIGN KEY (workflow_id)
    REFERENCES public.workflows (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_pitwd_project ON public.project_issue_type_workflow_defaults IS 'Esli udalyaetsya proekt, udalyayutsya vse svyazannye rabochie protsessy po umolchaniyu dlya proekta/tipa zadach.';
COMMENT ON CONSTRAINT fk_pitwd_issue_type ON public.project_issue_type_workflow_defaults IS 'Nelzya udalit tip zadachi, esli est svyazannye rabochie protsessy po umolchaniyu dlya proekta/tipa zadach.';
COMMENT ON CONSTRAINT fk_pitwd_workflow ON public.project_issue_type_workflow_defaults IS 'Nelzya udalit rabochiy protsess, opredelennyy po umolchaniyu dlya proekta/tipa zadach.';

ALTER TABLE IF EXISTS public.user_notification_settings
    ADD CONSTRAINT fk_user_notification_settings_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_user_notification_settings_user ON public.user_notification_settings IS 'Nelzya udalit polzovatelya, esli est svyazannye nastroyki uvedomleniya polzovatelya.';

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_recipient_user FOREIGN KEY (recipient_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_template FOREIGN KEY (template_id)
    REFERENCES public.notification_templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_issue FOREIGN KEY (issue_id)
    REFERENCES public.issues (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.notification_queue
    ADD CONSTRAINT fk_notification_queue_status FOREIGN KEY (status_id)
    REFERENCES public.notification_statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

COMMENT ON CONSTRAINT fk_notification_queue_recipient_user ON public.notification_queue IS 'Nelzya udalit polzovatelya, yavlyayushchimsya poluchatelem uvedomleniy.';
COMMENT ON CONSTRAINT fk_notification_queue_template ON public.notification_queue IS 'Nelzya udalit shablon uvedomleniy, po kotoromu est neotpravlennye uvedomleniya.';
COMMENT ON CONSTRAINT fk_notification_queue_issue ON public.notification_queue IS 'Esli udalyaetsya zadacha, udalyaetsya vsya svyazannaya ochered uvedomleniy.';
COMMENT ON CONSTRAINT fk_notification_queue_project ON public.notification_queue IS 'Esli udalyaetsya proekt, udalyaetsya vsya svyazannaya ochered uvedomleniy.';
COMMENT ON CONSTRAINT fk_notification_queue_status ON public.notification_queue IS 'Nelzya udalit status obrabotki uvedomleniya, po kotoromu est svyazannaya ochered uvedomleniy.';


-- ***********************************************************************************
--                              INDEXES FOR PERFORMANCE
-- ***********************************************************************************
CREATE INDEX IF NOT EXISTS idx_issues_project_id ON public.issues (project_id);
CREATE INDEX IF NOT EXISTS idx_issues_reporter_id ON public.issues (reporter_id);
CREATE INDEX IF NOT EXISTS idx_issues_assignee_id ON public.issues (assignee_id);
CREATE INDEX IF NOT EXISTS idx_issues_status_id ON public.issues (status_id);
CREATE INDEX IF NOT EXISTS idx_issues_issue_type_id ON public.issues (issue_type_id);
CREATE INDEX IF NOT EXISTS idx_issues_priority_id ON public.issues (priority_id);
CREATE INDEX IF NOT EXISTS idx_issues_created_at ON public.issues (created_at);
CREATE INDEX IF NOT EXISTS idx_issues_updated_at ON public.issues (updated_at);

CREATE INDEX IF NOT EXISTS idx_projects_lead_id ON public.projects (lead_id);
CREATE INDEX IF NOT EXISTS idx_projects_default_workflow_id ON public.projects (default_workflow_id);

CREATE INDEX IF NOT EXISTS idx_comments_issue_id ON public.comments (issue_id);
CREATE INDEX IF NOT EXISTS idx_comments_author_id ON public.comments (author_id);

CREATE INDEX IF NOT EXISTS idx_activity_log_issue_id ON public.activity_log (issue_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_action_type_id ON public.activity_log (action_type_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_user_id ON public.activity_log (user_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_created_at ON public.activity_log (created_at);

CREATE INDEX IF NOT EXISTS idx_attachments_issue_id ON public.attachments (issue_id);
CREATE INDEX IF NOT EXISTS idx_attachments_uploader_id ON public.attachments (uploader_id);

CREATE INDEX IF NOT EXISTS idx_issue_links_source_issue_id ON public.issue_links (source_issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_links_target_issue_id ON public.issue_links (target_issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_links_link_type_id ON public.issue_links (link_type_id);

CREATE INDEX IF NOT EXISTS idx_issue_watchers_issue_id ON public.issue_watchers (issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_watchers_user_id ON public.issue_watchers (user_id);

CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON public.role_permissions (role_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON public.role_permissions (permission_id);

CREATE INDEX IF NOT EXISTS idx_project_members_project_id ON public.project_members (project_id);
CREATE INDEX IF NOT EXISTS idx_project_members_group_id ON public.project_members (group_id);
CREATE INDEX IF NOT EXISTS idx_project_members_role_id ON public.project_members (role_id);

CREATE INDEX IF NOT EXISTS idx_project_issue_type_workflow_defaults_project_id ON public.project_issue_type_workflow_defaults (project_id);
CREATE INDEX IF NOT EXISTS idx_project_issue_type_workflow_defaults_issue_type_id ON public.project_issue_type_workflow_defaults (issue_type_id);
CREATE INDEX IF NOT EXISTS idx_project_issue_type_workflow_defaults_workflow_id ON public.project_issue_type_workflow_defaults (workflow_id);

CREATE INDEX IF NOT EXISTS idx_notification_templates_name ON public.notification_templates (name);

CREATE INDEX IF NOT EXISTS idx_user_notification_settings_user_id ON public.user_notification_settings (user_id);

CREATE INDEX IF NOT EXISTS idx_notification_queue_recipient_user_id ON public.notification_queue (recipient_user_id);
CREATE INDEX IF NOT EXISTS idx_notification_queue_status_id ON public.notification_queue (status_id);
CREATE INDEX IF NOT EXISTS idx_notification_queue_created_at ON public.notification_queue (created_at);

CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_statuses_default_only_one ON public.notification_statuses (is_default) WHERE is_default = TRUE;
COMMENT ON INDEX public.ux_notification_statuses_default_only_one IS 'Garantirovano mozhet byt tolko odin status so znacheniem po umolchaniyu TRUE.';

CREATE INDEX IF NOT EXISTS idx_groups_name ON public.groups (name);

CREATE INDEX IF NOT EXISTS idx_user_groups_user_id ON public.user_groups (user_id);
CREATE INDEX IF NOT EXISTS idx_user_groups_group_id ON public.user_groups (group_id);

COMMIT;

